# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

##### Vos Configurations
  config.vm.box = "debian-tp"

  # Ajout d'une interface réseau (privée)
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN2" 
 config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN4"


##### NE PAS MODIFIER CETTE PARTIE
  config.vm.hostname = File.basename(Dir.getwd)

### Dossiers partagés
  config.vm.synced_folder ".", "/vagrant", owner: "m1reseaux"
  config.vm.synced_folder "../partage", "/mnt/partage", create: true, owner: "m1reseaux" 


  config.vm.provider "virtualbox" do |vb|
  # Commenter pour s'exécuter sans GUI
    vb.gui = true

    vb.customize ["modifyvm", :id, "--memory", "768"]
  end

end

